Verbosity levels clarified, README updated

diff --git a/test/tst b/test/tst
--- a/test/tst
+++ b/test/tst
@@ -2,7 +2,7 @@
 #
 # T S T
 #
-# tst last edited on Fri Jun 21 23:26:28 2024 
+# tst last edited on Thu Mar 20 10:11:33 2025 
 #
 # To redirect both stdout and stderr to a file, use ampersand redirect operation, for example; -
 #  ./tst &> outputFile
@@ -17,8 +17,8 @@ echo "${TEN_PLUSS} $EXE -h  +++help option"
 echo "${TEN_PLUSS} Shell got Return code number $? for -h options check${TEN_PLUSS}"
 #
 # Test Debug option
-echo ""
-echo "${TEN_PLUSS} $EXE -D  +++Debug option" 
-../$EXE -D
-echo "${TEN_PLUSS} Shell got Return code number $? for -D options check${TEN_PLUSS}"
+#echo ""
+#echo "${TEN_PLUSS} $EXE -D  +++Debug option" 
+#../$EXE -D
+#echo "${TEN_PLUSS} Shell got Return code number $? for -D options check${TEN_PLUSS}"
 #
